[package]
name = "rusty_postman"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.97"
clap = { version = "4.5.32" }
clap_derive = "4.5.32"
